CREATE TABLE [dbo].[tbl_DistroEdition]
(
	[Id] [int] IDENTITY (1,1) NOT NULL,
	[EditionId] [int] NOT NULL,
	[DistroId] [int] NOT NULL,
	CONSTRAINT [PK_tbl_DistroEdition] PRIMARY KEY CLUSTERED
	(
		[Id] ASC
	) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
